-- EX 1 --

SELECT * FROM EMPLOYEES WHERE ADDRESS LIKE '%Elgin,IL%';

-- CORRECCIÓN --
SELECT F_NAME, L_NAME 
FROM EMPLOYEES 
WHERE ADDRESS LIKE '%Elgin,IL%';

-- EX 2 --

SELECT F_NAME, L_NAME 
FROM EMPLOYEES 
WHERE B_DATE LIKE '%197%'
ORDER BY F_NAME;

-- EX 3 --

SELECT F_NAME, L_NAME 
FROM EMPLOYEES 
WHERE DEP_ID = 5 
AND SALARY BETWEEN 60000 and 70000
ORDER BY F_NAME;

-- CORRECION --
SELECT *
FROM EMPLOYEES
WHERE (SALARY BETWEEN 60000 AND 70000) AND DEP_ID = 5;


